# Generated by Django 3.0.7 on 2020-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='settings.STATIC_ROOT/course/no-image.png', upload_to=''),
        ),
    ]
