# Generated by Django 3.0.7 on 2020-07-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200703_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/static/course/no-image.png', upload_to=''),
        ),
    ]
